import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        {children}
        <div className="fixed bottom-4 right-4 z-50 pointer-events-none text-white/50 text-sm font-bold select-none">
          armaansiddiqui
        </div>
      </body>
    </html>
  );
}
